services:
  institutional-website:
    ports:
      - mode: ingress
        target: 80
        published: 8001
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 40s
      timeout: 1s
      retries: 2
      start_period: 10s
    extra_hosts:
      - "www.farmacia.ufmg.br:10.10.10.1" # Use-se o Proxy Reverso por causa das requisições em HTTPS
      - "farmacia.ufmg.br:10.10.10.1" # Use-se o Proxy Reverso por causa das requisições em HTTPS

  intranet-website:
    ports:
      - mode: ingress
        target: 80
        published: 8002
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 40s
      timeout: 1s
      retries: 2
      start_period: 10s
    extra_hosts:
      - "intranet.farmacia.ufmg.br:10.10.10.1" # Use-se o Proxy Reverso por causa das requisições em HTTPS

  escuta-website:
    ports:
      - mode: ingress
        target: 80
        published: 8003
        protocol: tcp
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 40s
      timeout: 1s
      retries: 2
      start_period: 10s
    extra_hosts:
      - "escuta.farmacia.ufmg.br:10.10.10.1" # Use-se o Proxy Reverso por causa das requisições em HTTPS

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer_agent:
    image: portainer/agent:2.27.7
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host

  db:
    image: mysql:5.7
    command:
      # - "--default-authentication-plugin=mysql_native_password" # Is not necessary for WP 5.4+
      - "--innodb-file-per-table=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--max_allowed_packet=64M"
      - "--innodb_buffer_pool_size=1G"
    restart: always
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - type: volume
        source: database-volume
        target: /var/lib/mysql
      # To load a mysql dump (anyname.sql.gz):
      - type: bind
        source: ./db/initdb.d/
        target: /docker-entrypoint-initdb.d/
    environment:
      # MYSQL_DATABASE: ${AWESOME_MYSQL_DATABASE}
      # MYSQL_USER: ${AWESOME_MYSQL_USER}
      # MYSQL_PASSWORD: ${AWESOME_MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      # MYSQL_DB_PASSWORD_FILE: /run/secrets/db-root-pass
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1.5"
    #       memory: 512M
    #     reservations:
    #       cpus: "1"
    #       memory: 1024M
    # secrets:
    #   - db-root-pass

volumes:
  database-volume:
